### PR TITLE
Bump version to v0.1.0

### PR DESCRIPTION
**Pull request by junaire**

### CODE REVIEW

**Comment by Xuanwo** [comment]
How about update README.md too? Take `go-service-s3` as an example.

**Comment by junaire** [comment]
What is this? Should I remove it?
image

**Comment by Xuanwo** [comment]
> What is this? Should I remove it?
> image

It's our integration tests, I think we need to use `https://teamcity.beyondstorage.io/app/rest/builds/buildType:(id:Services_Gdrive_IntegrationTests)/statusIcon`

**Comment by Xuanwo** [comment]
Maybe we can add a link to the matrix go-storage room? `https://matrix.to/#/#beyondstorage@go-storage:matrix.org`

**Comment by junaire** [comment]
Now it seems to look good!
image

**Pull request merged**
