### PR TITLE
fix: integration tests failed

### LINKED ISSUE #25: Integration test failed with invalid value
See https://github.com/beyondstorage/go-service-gdrive/pull/24#issuecomment-915368436

### PR DESCRIPTION
**Pull request by junaire**
close #25

### CODE REVIEW

**Comment by junaire** [comment]
The integration tests still fails, and it keeps complaining about 400 error. I don't know why and I'm struggling with debugging go test in CLI...

I'm running the tests in the remote machine cuz there is something wrong with my local laptop, network issue I mean...

**Comment by junaire** [comment]
Looks like we almost there!
```
go test -race -count=1 -covermode=atomic -v ./tests
=== RUN   TestStorage
    utils_test.go:15: Setup test for gdrive

  Given a basic Storager ✔
    When String called 
      The string should not be empty ✔✔
    When Metadata called 
      The metadata should not be empty ✔✔
    When Read a file 
      The error should be nil ✘ ✔
    When Write a file 
      The first returned error should be nil ✔ ✔
    When Stat a file 
      The error should be nil ✔ ✔
    When Delete a file  ✔
    When List an empty dir 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The next should be done ✘✔
      The object should be nil ✘✔
    When List a dir within files 
      The error should be nil ✔ ✔
    When List without ListMode 
      The error should be nil ✔


Errors:

  * /root/go-service-gdrive/tests/storage_test.go 
  Line 14: - runtime error: index out of range [0] with length 0 
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/go-service-gdrive# 
```

**Comment by junaire** [comment]
Till this moment, `Storager` has passed the most parts of integration tests. However, there are still some problems I can not handle. 
```
❯ make integration_test
go test -race -count=1 -covermode=atomic -v ./tests
=== RUN   TestStorage
    utils_test.go:15: Setup test for gdrive

  Given a basic Storager ✔
    When String called 
      The string should not be empty ✔✔
    When Metadata called 
      The metadata should not be empty ✔✔
    When Read a file 
      The error should be nil ✔✔
      The content should be match ✔✔✔✔
    When Write a file 
      The first returned error should be nil ✔✔
      The second returned error also should be nil ✔✔
      Stat should get Object without error 
        The error should be nil ✔✔
        The name and size should be match ✔✔✔✔✔
      Read should get Object data without error 
        The error should be nil ✔✔
        The content should be match ✔✔✔✔
    When Stat a file 
      The error should be nil ✔✔
      The Object name and size should be match ✔✔✔✔✔
    When Delete a file 
      The first returned error should be nil ✔✔
      The second returned error also should be nil ✔✔
      Stat should get nil Object and ObjectNotFound error ✔✔✔
    When List an empty dir 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The next should be done ✘✔
      The object should be nil ✘✔
    When List a dir within files 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The name and size should be match ✔✔✘✔
    When List without ListMode 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The name and size should be match ✔✔✘

```
In the integration tests, we ask gdrive service to list an empty directory, which is `""`. In this case, we actually list the absolute path right? I mean `workDir`. I take a look of tests, and it says the return value should be `nil`. However, I find there are files returned by gdrive API after step into the code! Is there something I misunderstood? Please leave a comment if anyone knows why...

**Comment by junaire** [comment]
We finally made it! All tests passed now, can you please review this patch? @Xuanwo 
```
❯ make integration_test
go test -race -count=1 -covermode=atomic -v ./tests
=== RUN   TestStorage
    utils_test.go:15: Setup test for gdrive

  Given a basic Storager ✔
    When String called 
      The string should not be empty ✔✔
    When Metadata called 
      The metadata should not be empty ✔✔
    When Read a file 
      The error should be nil ✔✔
      The content should be match ✔✔✔✔
    When Write a file 
      The first returned error should be nil ✔✔
      The second returned error also should be nil ✔✔
      Stat should get Object without error 
        The error should be nil ✔✔
        The name and size should be match ✔✔✔✔✔
      Read should get Object data without error 
        The error should be nil ✔✔
        The content should be match ✔✔✔✔
    When Stat a file 
      The error should be nil ✔✔
      The Object name and size should be match ✔✔✔✔✔
    When Delete a file 
      The first returned error should be nil ✔✔
      The second returned error also should be nil ✔✔
      Stat should get nil Object and ObjectNotFound error ✔✔✔
    When List an empty dir 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The next should be done ✔✔
      The object should be nil ✔✔
    When List a dir within files 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The name and size should be match ✔✔✔✔✔
    When List without ListMode 
      The error should be nil ✔✔
      The iterator should not be nil ✔✔
      The name and size should be match ✔✔✔✔


67 total assertions

--- PASS: TestStorage (178.26s)
=== RUN   TestCopier
    utils_test.go:15: Setup test for gdrive

  Given a basic Storager ✔
    When Copy a file 
      The error should be nil ✔✔
      Read should get dst object data without error 
        The error should be nil ✔✔
        The content should be match ✔✔✔✔
    When Copy to an existing file 
      The error should be nil ✔✔
      Read should get dst object data without error 
        The error should be nil ✔✔
        The content should be match ✔✔✔


83 total assertions

--- PASS: TestCopier (116.02s)
PASS
coverage: [no statements]
ok      github.com/beyondstorage/go-service-gdrive/tests        294.372s        coverage: [no statements]
```

**Comment by Xuanwo** [comment]
image

Congrets!

**Pull request merged**
